/**
* InfantryProgram
*
* TNA-Community
* https://discord.gg/Zs23URtjwF
* © 2021 {|||TNA|||}WAKeupneo
*
* This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License. 
* To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/4.0/.
* Do Not Re-Upload
*/


// action = "openMap true; onMapSingleClick { onMapSingleClick {}; [player,_pos,'sab_C130_J',1] remoteExec ['WMS_fnc_ParadropMissionRequest']; openMap false; true };";
// [player,_pos,"UK3CB_BAF_Merlin_HC4_CSAR",0,"INFbyChopper"] remoteExec ["WMS_fnc_InfantryProgram_INFbyChopper"];
// _pos is generated by onMapSingleClick

if (WMS_InfantryProgram_LOGs) then {diag_log format ["[INFANTRY by CHOPPER]|TNA|TNA|TNA|TNA|TNA| _this check, _this = %1", _this]};

private _target = (_this select 0);
private _pos = (_this select 1); 
private _plane = selectRandom WMS_DeliveryChopper_Type;
private _empty = (_this select 3);
private _missionType = (_this select 4);
private _patrolLoadout = selectrandom [WMS_Loadout_AOR2, WMS_Loadout_M90, WMS_Loadout_Scorpion, WMS_Loadout_Tiger, WMS_Loadout_UKtmp, WMS_Loadout_UKwdl, WMS_Loadout_FRce, WMS_Loadout_DEfleck];
private _RandomPosSpawn = [_target, 1500, 2500] call BIS_fnc_findSafePos;
private _RandomPosDest = [_pos, 0, 150, 20, 0, 0.15, 0, [], [_pos,[]]] call BIS_fnc_findSafePos;
private _RandomPosEnd = [_RandomPosDest, worldSize, (worldSize*1.2)] call BIS_fnc_findSafePos;
private _amount = 999;
private _WPtype = "TR UNLOAD";
if (worldName == "Tanoa") then {_patrolLoadout = selectrandom [WMS_Loadout_AOR2, WMS_Loadout_M90, WMS_Loadout_Scorpion, WMS_Loadout_Tiger, WMS_Loadout_DEfleck];};

    if (_missionType == "INFbyChopper" ) then {_amount = 5000} else {
      if (_missionType == "WDtrader" ) then {_amount = 1500} else {
      
    };
    };
    private _lockerMoney = _target getVariable ['ExileLocker', 0];
    if(_lockerMoney > _amount) then
    { 
		_lockerMoney1 = _target getVariable ['ExileLocker', 0];
    _playerMoney = _target getVariable ['ExileMoney', 0];
		_lockerMoney = _lockerMoney1 - _amount;
		_poptabsplayer = _playerMoney + _lockerMoney;
		_target setVariable ['ExilePopTabsCheck', _poptabsplayer];
		_target setVariable ['ExileMoney', _playerMoney, true];
		_target setVariable ['ExileLocker', _lockerMoney, true];
    	format['updateLocker:%1:%2', _lockerMoney, (getPlayerUID _target)] call ExileServer_system_database_query_fireAndForget;

private _vhl = [_RandomPosSpawn, (random 359), _plane, BLUFOR] call bis_fnc_spawnvehicle; //0:created vehicle (Object), 1:all crew (Array of Objects), 2:vehicle's group
private _vehic = (_vhl select 0);
private _grp = (_vhl select 2);
private _vehicVarName = format["CHOPPA_%1_%2", getplayerUID _target, time];
_vehic setvehicleVarName _vehicVarName;
_vehic setVehicleLock "LOCKEDPLAYER";
if (_missionType == "INFbyChopper" ) then {
  [_target,_RandomPosDest,_vhl,_missionType,(round(2+(random 3))),_patrolLoadout,600,250] call WMS_fnc_InfantryProgram_INFsquad;
} else { 
if (_missionType == "WDtrader" ) then {
  [_target,_RandomPosDest,300,_vhl] call WMS_fnc_InfantryProgram_WDtrader;
} else { }};
clearMagazineCargoGlobal _vehic;
clearWeaponCargoGlobal _vehic;
clearItemCargoGlobal _vehic;
clearBackpackCargoGlobal _vehic;     

_vehic flyInHeight WMS_IP_Extract_Alt;
WMS_INFbyChopper_LastTime = time;
publicVariable "WMS_INFbyChopper_LastTime";

private _Helipad_1 = "Land_HelipadEmpty_F" createVehicle _RandomPosDest;
private _GreenSmoke = "SmokeShellOrange" createVehicle _RandomPosDest;
{
  removeAllItems _x;
  removeAllWeapons _x;
  removeBackpackGlobal _x;
  _x forceAddUniform "AOR2_Camo_Cyre";
  _x addVest "AOR2_Vest_1";
  _x additem "FirstAidKit";
  _x addGoggles "G_Balaclava_oli";
  _x disableAI "AUTOTARGET";
  _x disableAI "TARGET";
  _x disableAI "AUTOCOMBAT";
  _x allowfleeing 0;
} forEach units _grp ;

private _WPT_INFbyCHOPPER1 = _grp addWaypoint [_RandomPosDest, 0];
_WPT_INFbyCHOPPER1 setWaypointType _WPtype;
_WPT_INFbyCHOPPER1 setWaypointCombatMode "BLUE";
_WPT_INFbyCHOPPER1 setWaypointbehaviour  "CARELESS";
waitUntil  {(_vehic distance2D _RandomPosDest) <= 200};
["toastRequest", ["InfoTitleAndText", [format ["Incoming %1, Infantry Reinforcement Chopper",(typeof _vehic)]]]] call ExileServer_system_network_send_broadcast;
//[_grp, _RandomPosDest, _Helipad_1] spawn BIS_fnc_wpLand;
waituntil {_vehic distance _Helipad_1 <=5};
uisleep 5;
_vehic flyInHeight WMS_IP_Extract_Alt;

private _WPT_INFbyCHOPPER2 = _grp addWaypoint [_RandomPosEnd, 150];
_WPT_INFbyCHOPPER2 setWaypointType "MOVE";

0 = [_vehic, _RandomPosDest, _grp] spawn {
 waituntil  {(_this select 0) distance2d (_this select 1) <= 200};
 uisleep (round(120+(random 60)));
 (_this select 0) setfuel 0;
 (_this select 0) setdamage 0.9;
 {deletevehicle _x} foreach units(_this select 2);
};
1 = [_vehic, _grp, _WPT_INFbyCHOPPER1, _WPT_INFbyCHOPPER2, _Helipad_1] spawn {
 waituntil  {!(alive (_this select 0))};
 //[_group,[_vehicles],[_markers],[_waypoint]] call WMS_fnc_Ivl2_cleanup;
 [(_this select 1),[(_this select 4)],[],[(_this select 2),(_this select 3)]] call WMS_fnc_lvl2_cleanup;
};

    } else {
      if (WMS_InfantryProgram_LOGs) then {
 	    diag_log format ["[INFANTRY by CHOPPER]|TNA|TNA|TNA|TNA|TNA|  %1 too poor to get a chopper |TNA|TNA|TNA|TNA|TNA|", _target];
      };
    };