/**
* InfantryProgram
*
* TNA-Community
* https://discord.gg/Zs23URtjwF
* © 2021 {|||TNA|||}WAKeupneo
*
* This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License. 
* To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/4.0/.
* Do Not Re-Upload
*/

// action = "openMap true; onMapSingleClick { onMapSingleClick {}; [player,_pos,'sab_C130_J',1] remoteExec ['WMS_fnc_ParadropMissionRequest']; openMap false; true };";
//[player,_pos,nil,0,_vehicVarName] remoteExec ["WMS_fnc_infantryProgram_extraction"];
// _pos is generated by onMapSingleClick
diag_log format ["[EXTRACTION CHOPPER]|TNA|TNA|TNA|TNA|TNA| Chopper Transport _this check, _this = %1 |TNA|", _this];

params [
  "_target",
  "_pos",
  ["_plane",(selectRandom WMS_ExtractionChopper_Type)],
  ["_zero",0], //WTF is this 0 for ???
  ["_vehicVarName","fuckingDumbName"] //WTF is this _vehicVarName for ???
];
if !(typeName _pos == "ARRAY") exitWith {diag_log format ["[EXTRACTION CHOPPER]|TNA|TNA|TNA|TNA|TNA| Chopper Transport _pos fuckedup %1", _pos];};
private _RandomPosSpawn = [_target, 1500, 2500] call BIS_fnc_findSafePos;
private _RandomPosExtract = [_target, 0, 100, 20, 0, 0.15, 0, [], [(position _target),[]]] call BIS_fnc_findSafePos;
private _RandomPosDest = [_pos, 0, 200, 20, 0, 0.15, 0, [], [_pos,[]]] call BIS_fnc_findSafePos;
private _RandomPosEnd = [_RandomPosDest, worldSize, (worldSize*1.2)] call BIS_fnc_findSafePos;

private _vhl = [_RandomPosSpawn, (0+random 359), _plane, BLUFOR] call bis_fnc_spawnvehicle;
private _vehic = (_vhl select 0);
private _grp = (_vhl select 2);
clearMagazineCargoGlobal _vehic;
clearWeaponCargoGlobal _vehic;
clearItemCargoGlobal _vehic;
clearBackpackCargoGlobal _vehic;
if (_plane == "UK3CB_BAF_Wildcat_AH1_TRN_8A") then {_vehic setObjectTextureGlobal [0,"r3f_retex\data\lynx\heli_light_03_ce_r3f_co.paa"]};
if (_plane == "UK3CB_BAF_Merlin_HC3_32") then {_vehic setObjectTextureGlobal [0,"r3f_retex\data\merlin\heli_transport_02_ce_1_r3f_co.paa"]};

_vehic lockDriver true; 
_vehic lockTurret [[-1], true]; 
_vehic lockTurret [[0], true]; 
//_vehic lockTurret [[1], true]; 
 
_vehic flyInHeight WMS_IP_Extract_Alt;
WMS_Extraction_Chopper_LastTime = time;
publicVariable "WMS_Extraction_Chopper_LastTime";

private _Helipad_1 = "Land_HelipadEmpty_F" createVehicle _RandomPosExtract;
private _GreenSmoke = "SmokeShellGreen" createVehicle _RandomPosExtract;
private _Helipad_2 = "Land_HelipadCircle_F" createVehicle _RandomPosDest;
{
  removeAllItems _x;
  removeAllWeapons _x;
  removeBackpackGlobal _x;
  _x additem "FirstAidKit";
  _x disableAI "AUTOTARGET";
  _x disableAI "TARGET";
  _x disableAI "AUTOCOMBAT";
} forEach units _grp ;

private _WPT_paradrop = _grp addWaypoint [_RandomPosExtract, 0];
_WPT_paradrop setWaypointType "LOAD";
_WPT_paradrop setWaypointCombatMode "BLUE";
_WPT_paradrop setWaypointbehaviour  "CARELESS";
waitUntil  {(_vehic distance2D _RandomPosExtract) <= 200 || !(alive _vehic)}; //NEED A TRIGGER
if (WMS_exileToastMsg) then {["toastRequest", ["InfoTitleAndText", [format ["Incoming %1 Extraction Chopper",(typeof _vehic)]]]] call ExileServer_system_network_send_broadcast};
[_grp, _RandomPosExtract, _Helipad_1] spawn BIS_fnc_wpLand; //I think there is an error with this one
waitUntil {!(vehicle _target == _target) || !(alive _target) || !(alive _vehic)};
uisleep 5;

private _WPT_paradrop1 = _grp addWaypoint [_RandomPosDest, 0];
_WPT_paradrop1 setWaypointType "TR UNLOAD";
_WPT_paradrop1 setWaypointCombatMode "BLUE";
_WPT_paradrop1 setWaypointbehaviour  "CARELESS";
waitUntil  {(_vehic distance2D _RandomPosDest) <= 200 || !(alive _vehic)};
uisleep 45;
_vehic flyInHeight WMS_IP_Extract_Alt;

private _WPT_paradrop2 = _grp addWaypoint [_RandomPosEnd, 150];
_WPT_paradrop2 setWaypointType "MOVE";
_WPT_paradrop2 setWaypointCombatMode "BLUE";
_WPT_paradrop2 setWaypointbehaviour  "CARELESS";
[units _grp] domove _RandomPosEnd;

//Those "waitUntil" are really fucked up
[_vehic, _pos, _grp, _WPT_paradrop, _RandomPosDest, _WPT_paradrop2, _Helipad_1, _Helipad_2] spawn {
 waituntil  {(_this select 0) distance2d (_this select 4) <= 200 || !(alive (_this select 0))};
 uisleep 60;
 systemchat format ["%1 Extraction done.",(_this select 0)];
if (WMS_exileToastMsg) then {["toastRequest", ["InfoTitleAndText", [format ["%1 Extraction Done",(typeof (_this select 0))]]]] call ExileServer_system_network_send_broadcast};
 uisleep (60+random 60);
 (_this select 0) setfuel 0;
 (_this select 0) setdamage 0.9;
 {deletevehicle _x} foreach units(_this select 2);
};
[_vehic, _grp, _WPT_paradrop, _WPT_paradrop1, _WPT_paradrop2, _Helipad_1, _Helipad_2] spawn {
 waituntil  {!(alive (_this select 0)) || !(alive (_this select 0))};
if (WMS_exileToastMsg) then {["toastRequest", ["InfoTitleAndText", [format ["%1 Extraction Done",(typeof (_this select 0))]]]] call ExileServer_system_network_send_broadcast};
 [(_this select 1),[(_this select 5),(_this select 6)],[],[(_this select 2),(_this select 3),(_this select 4)]] call WMS_fnc_lvl2_cleanup;
};